parameters:
    ag_jawbone_up_interface.client_id: ''
    ag_jawbone_up_interface.client_secret: ''
    ag_jawbone_up_interface.callback: ''
    ag_jawbone_up_interface.scopes: []
    ag_jawbone_up_interface.configuration: []
services:
    ag.jawbone.up.interface:
        class:     AG\JawboneUPInterfaceBundle\Jawbone\ApiGatewayFactory
        arguments:
            - %ag_jawbone_up_interface.client_id%
            - %ag_jawbone_up_interface.client_secret%
            - %ag_jawbone_up_interface.callback%
            - %ag_jawbone_up_interface.scopes%
            - %ag_jawbone_up_interface.configuration%
            - @router
